name: Deploy static content to Pages

on:
  push:
    branches: ["main"] # main ব্রাঞ্চে পুশ হলে CI রান করবে
  workflow_dispatch: # ম্যানুয়ালি রান করার জন্য

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # আপনার index.html যে ফোল্ডারে আছে (রুট ডিরেক্টরি হলে '.')
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
